### ISSUE TITLE
Quantal is not supported anymore

### ISSUE THREAD

**Issue by sroddy** [Kloadut/dokku-md-dockerfiles#4]
Hi,
apt-get update command fails because in the official 5.5 MariaDB ubuntu repo, Quantal is not supported anymore.

If I change the repo url to

deb http://archive.mariadb.org/mariadb-5.5.38/repo/ubuntu/ quantal main

everything works as expected

**Comment by motin** [comment]
Changing the repo url must only be considered a workaround since Quantal is not supported anymore (that mariadb archive server has a very low bandwidth it seems as well). The only real solution is to use Ubuntu Trusty going forward. I recently attempted this in https://github.com/motin/dokku-md-dockerfiles/tree/upgrade-to-trusty
